### ISSUE TITLE
can we change the surface type (from 360 to normal view) at runtime?

### ISSUE THREAD

**Issue by amer360** [FinweLtd/orion360-sdk-pro-examples-android#12]
Can we change the surface type from 360 degrees to be a normal (2d) preview?

The problem is that I need to display a video ad in the middle of the video, but the ad is shown in 360 mode.
so we need to change the type when the ad starts, and change it back to the surface type(360) once the ad is complete.

I tried to change the projection type as you mentioned in the doc, but it didn't work

Thanks in advance

**Comment by amer360** [comment]
Dear @trantako , your quick response is highly appreciated

Thank you

**Comment by amer360** [comment]
Dear @trantako  , your quick response is highly appreciated

Thank you

**Comment by trantako** [comment]
There is now a separate document that discusses ads (SERVING_ADS.md) as well as 5 examples of different approaches.

Closing the issue.
