### ISSUE TITLE
Passing Secured Streaming URLs from AWS

### ISSUE THREAD

**Issue by Tamimi360** [FinweLtd/orion360-sdk-pro-examples-android#13]
We're trying to play secured video streaming urls from AWS through injecting their signed CDN (Cloudfront) URLs 
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html

To be able to secured video streaming urls that with Native Mobile Apps we need to pass signed cookies through a custom HTTP Headers from the Player side, however Orion Player doesn't offer this as an option.

Clarifying about passing Custom Headers, in the reference below ExoPlayer, shows how we can do that
https://exoplayer.dev/customization.html

Kindly, advice how can sort out this issue with Orion Player?

**Comment by Tamimi360** [comment]
Hello @trantako 
Kindly any updates regarding my enquiry?

**Comment by trantako** [comment]
There is now a document (SECURE_STREAMING.md) as well as an example that discuss secure streaming from AWS and show how it can be done.

Closing the issue.
