### ISSUE TITLE
RTSP Streaming

### ISSUE THREAD

**Issue by gdsomia** [FinweLtd/orion360-sdk-pro-examples-android#2]
I need to stream a live video from Wowza server usng RTSP streaming protocol. Does Orion360 pro version support it? Also the livestream can be a 360 video streaming or a normal streaming from the Wowza. Does the SDK supports normal video streaming as well?

**Comment by trantako** [comment]
Currently Orion360 Pro for Android supports only streaming over HTTP/HTTPS. 

You can stream either .mp4 files (that should be encoded with web/progressive mode enabled) or .m3u8 adaptive HLS streams.

Android MediaPlayer and Google ExoPlayer are the backends used for streaming and decoding video in Orion360, and neither one supports RTMP/RTSP protocols properly. Meaning that another library would need to be integrated to support them. So far there has been little very demand for RTMP/RTSP, but this is now slowly changing and we may add support in a later release.
