### ISSUE TITLE
Hotspot

### ISSUE THREAD

**Issue by ashokkumarmr1** [FinweLtd/orion360-sdk-pro-examples-android#4]
Hi boss, how can i add hotspot

**Comment by trantako** [comment]
If you only need to add an image icon on top of the panorama, check out this example that shows how to add an OrionSprite:
https://github.com/FinweLtd/orion360-sdk-pro-examples-android/blob/master/app/src/main/java/fi/finwe/orion360/sdk/pro/examples/sprite/ImageSprite.java

If you also want to have interaction, for example focus animation and selection by tapping the hotspot or by looking at it, then you want to use the component specifically made for these needs: SelectablePointerIcon. Check out hotspot related parts from the touch example:
https://github.com/FinweLtd/orion360-sdk-pro-examples-android/blob/master/app/src/main/java/fi/finwe/orion360/sdk/pro/examples/input/Touch.java
